package co.artsoft.arqui.migrania.controller;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import co.artsoft.arqui.migrania.dao.FoodDAO;
import co.artsoft.arqui.migrania.dao.MigraineDAO;
import co.artsoft.arqui.migrania.entity.Food;
import co.artsoft.arqui.migrania.entity.FoodViewModel;
import co.artsoft.arqui.migrania.entity.Migraine;
import co.artsoft.arqui.migrania.entity.MigraniaViewModel;
import co.artsoft.arqui.migrania.entity.Test;

@RestController
@RequestMapping(path = "/json")
public class JsonController {
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private FoodDAO foodRepository;
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private MigraineDAO mnigraineRepository;
	
	@RequestMapping("/thing")
	public Migraine myThing(){
		Migraine migraine = new Migraine();
		return migraine;
	}
	
	/*@RequestMapping(value="/test",method = RequestMethod.POST)
	public ResponseEntity<?> addPerson(@RequestBody Test person) {
		
		Food n = new Food();
		//n.setDate(new java.sql.Date(System.currentTimeMillis()));
		Set<Food> foods = new HashSet<Food>();
		for(Food f : person.getFoods()) {
			Food g = foodRepository.save(f);	
			foods.add(g);
		}
		//n.setFoods(g);
		return new ResponseEntity<>(foods, HttpStatus.CREATED);
		//return new ResponseEntity<>(personRepo.save(person), HttpStatus.CREATED);
	}*/
	
	/*@RequestMapping(value="/test",method = RequestMethod.POST)
	public @ResponseBody addPerson(@RequestBody Test person) {
		String h = "aa";		
		return person;
		return new ResponseEntity<>(person, HttpStatus.CREATED);
		//return new ResponseEntity<>(personRepo.save(person), HttpStatus.CREATED);
	}	*/
	
	@RequestMapping(value="/test",method = RequestMethod.POST)
	public ResponseEntity<?> addPerson(@RequestBody MigraniaViewModel person) {
		Migraine migraine = new Migraine();
		migraine.setSleepPattern(person.getSleepPattern());
		migraine.setAudioFile(person.getAudioFile());
		migraine.setPainLevel(person.getPainLevel());
		
		Set<Food> foods = new HashSet<Food>();
		if (person.getFoods() != null && person.getFoods().size() > 0) {
			for(FoodViewModel f : person.getFoods()) {
				Food food = new Food();
				food.setName(f.getName());
				foods.add(food);			
			}			
			migraine.setFoods(foods);			
		}					
		migraine.setDate(new java.sql.Date(System.currentTimeMillis()));		
		Migraine g = mnigraineRepository.save(migraine);
		//n.setFoods(g);
		return new ResponseEntity<>(g, HttpStatus.CREATED);
		//return new ResponseEntity<>(personRepo.save(person), HttpStatus.CREATED);
	}
}


