package co.artsoft.arqui.migrania.controller;

import java.sql.Date;
import java.util.concurrent.atomic.AtomicLong;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import co.artsoft.arqui.migrania.dao.MigraineDAO;
import co.artsoft.arqui.migrania.entity.Migraine;
import co.artsoft.arqui.migrania.entity.TestJson;

@RestController
public class TestJsonController {
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private MigraineDAO episodioRepository;
	
    private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();
	
	@RequestMapping("/testISM")
	public Migraine test(@RequestParam(value="date", defaultValue="2017-06-19") Date date,
			@RequestParam(value="painLevel", defaultValue= "1") int painLevel,
			@RequestParam(value="audioFile", defaultValue="/foo") String audioFile,
			@RequestParam(value="sleepPattern", defaultValue="foo") String sleepPattern) {
				
		Migraine mi = new Migraine();
		
		mi.setDate(date);
		mi.setPainLevel(painLevel);
		mi.setAudioFile(audioFile);
		mi.setSleepPattern(sleepPattern);
				
		episodioRepository.save(mi);
	    return mi;
	}
}
